import { NavBar } from "@/components/Navbar";
import { TaskProvider } from "@/context/TasksContext";
import { Toaster } from "./Toaster";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import 'tailwindcss/tailwind.css';

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body className="m-0 p-0 flex flex-col min-h-screen bg-slate-800">
        <TaskProvider >
          <NavBar />
          <main className="flex-1 p-4 h-5/6 px-28 py-10">{children}</main>
          <Toaster />
        </TaskProvider>
      </body>
    </html>
  );
}

